# typed: false
# frozen_string_literal: true

# Homebrew formula for Ma'at — documentation-as-code for humans and AI agents.
# Auto-generated by scripts/render-homebrew-formula.sh on each release.
# Do not edit by hand; changes are overwritten on the next release.
class Maat < Formula
  desc "Documentation-as-code for humans and AI agents"
  homepage "https://github.com/getmaat/maat"
  version "0.4.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/getmaat/maat/releases/download/v0.4.0/maat_0.4.0_darwin_arm64.tar.gz"
      sha256 "aae02e366ab910af597a55359f3cbd11bef8b70baaffc06c13df50d7f8cb3de7"
    end
    on_intel do
      url "https://github.com/getmaat/maat/releases/download/v0.4.0/maat_0.4.0_darwin_amd64.tar.gz"
      sha256 "82560f76adadf4e3166f6e80b01e44a41ff0ea19f719904d86a253f213674485"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getmaat/maat/releases/download/v0.4.0/maat_0.4.0_linux_arm64.tar.gz"
      sha256 "b3f87c7c74264455905c10d9c40cd2c72331de94c94d2d871a7e24c8b71bd027"
    end
    on_intel do
      url "https://github.com/getmaat/maat/releases/download/v0.4.0/maat_0.4.0_linux_amd64.tar.gz"
      sha256 "abdf1dce55be78a4df5315a8f1c50eff98805383b3438c5bfba570a5089384ed"
    end
  end

  def install
    bin.install "maat"
  end

  test do
    assert_match "maat #{version}", shell_output("#{bin}/maat --version")
  end
end
