# typed: false
# frozen_string_literal: true

# Homebrew formula for Ma'at — documentation-as-code for humans and AI agents.
# Auto-generated by scripts/render-homebrew-formula.sh on each release.
# Do not edit by hand; changes are overwritten on the next release.
class Maat < Formula
  desc "Documentation-as-code for humans and AI agents"
  homepage "https://github.com/getmaat/maat"
  version "0.3.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/getmaat/maat/releases/download/v0.3.0/maat_0.3.0_darwin_arm64.tar.gz"
      sha256 "ed33df9acfd2f18c0da7c86b8cf0334d0bf6a87983ead451d3407f2835611c09"
    end
    on_intel do
      url "https://github.com/getmaat/maat/releases/download/v0.3.0/maat_0.3.0_darwin_amd64.tar.gz"
      sha256 "74ed0bdf990e91ded3bd9683a1c2b76db9189eb0d6fbc4738729b5a5bd2f2f80"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getmaat/maat/releases/download/v0.3.0/maat_0.3.0_linux_arm64.tar.gz"
      sha256 "74b53a70efd458d41ab0539f727615b40bc28c8ac0444dadc502c3fbe5178eb2"
    end
    on_intel do
      url "https://github.com/getmaat/maat/releases/download/v0.3.0/maat_0.3.0_linux_amd64.tar.gz"
      sha256 "dd786201e845254add0e3550015a3eaf05499b4b46fc537c82e7e3f8df2761cc"
    end
  end

  def install
    bin.install "maat"
  end

  test do
    assert_match "maat #{version}", shell_output("#{bin}/maat --version")
  end
end
