# typed: false
# frozen_string_literal: true

# Homebrew formula for Ma'at — documentation-as-code for humans and AI agents.
# Auto-generated by scripts/render-homebrew-formula.sh on each release.
# Do not edit by hand; changes are overwritten on the next release.
class Maat < Formula
  desc "Documentation-as-code for humans and AI agents"
  homepage "https://github.com/getmaat/maat"
  version "0.6.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/getmaat/maat/releases/download/v0.6.0/maat_0.6.0_darwin_arm64.tar.gz"
      sha256 "29eb683c0cbbc80a74ad97dd3d988b73cda3c1c431bbc9229991804509045f68"
    end
    on_intel do
      url "https://github.com/getmaat/maat/releases/download/v0.6.0/maat_0.6.0_darwin_amd64.tar.gz"
      sha256 "79985f8b5149609ffac4dc9c9f283e408563d3ea75d03060fbfd83d21f19284d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/getmaat/maat/releases/download/v0.6.0/maat_0.6.0_linux_arm64.tar.gz"
      sha256 "ef92d22f423a77815dca9683e2c7d5762bf70a70a991b9b4150894348122c9cd"
    end
    on_intel do
      url "https://github.com/getmaat/maat/releases/download/v0.6.0/maat_0.6.0_linux_amd64.tar.gz"
      sha256 "7ad2e29f104bc3ab762ffb448ddc24d4515bb4d821f5ab1ce4626d35c3d7620e"
    end
  end

  def install
    bin.install "maat"
  end

  test do
    assert_match "maat #{version}", shell_output("#{bin}/maat --version")
  end
end
